window.alphabet = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', 'Z'];

window.countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Arzebaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Carpe Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Cook Islands", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Nagorno-Karabakh", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Sahrawi Arab Democratic Republic", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Peincipe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Serbia Leone", "Singapore", "Slovenia", "Slovenia", "Solomon Islands", "Somalia", "Somaliland", "South Korea", "South Ossetia", "South Sudan", "Spain", "Sri Lanka", "Sudan", "South Sudan", "South Korea", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Transnistria", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"];

window.capitalCities = ["Abu Dhabi", "Abuja", "Accra", "Adamstown", "Addis Ababa", "Algiers", "Alofi", "Amman", "Amsterdam", "Andorra", "Antananarivo", "Apia", "Ashgabat", "Asmara", "Astana", "Asuncion", "Athens", "Avaru", "Baghdad", "Baku", "Bamako", "Bandar Seri Begawan", "Bangkok", "Bangui", "Banjul", "Basse Terre", "Beijing", "Beirut", "Belgrade", "Belmopan", "Berlin", "Bern", "Bishkek", "Bissau", "Bloemfontein","Bogota", "Brasilia", "Bratislava", "Brazzaville", "Bridgetown", "Brussels", "Bucharest", "Budapest", "Buenos Aires", "Bujumbura", "Cairo", "Canberra", "Cape Town", "Caracas", "Castries", "Cayenne", "Charlotte Amalie", "Chisinau", "Cockburn Town", "Canakry", "Copenhagen", "Dakar", "Damascus", "Dhaka", "Dili", "Djibouti", "Dodoma", "Doha", "Douglas", "Dushanbe", "East Jerusalem", "Edinburgh of the Seven Seas", "El Aaiun", "Tifariti", "Episkopi Cantonment", "Flying Fish Gove", "Fort de France", "Freetown", "Funafuti", "Gaborone", "George Town", "Georgetown", "Gibraltar", "Guatemala City", "Gustavia Saint", "Hagatna", "Hamilton", "Hanga Roa", "Hanoi", "Hamilton", "Harare", "Hargeisa", "Havana", "Helsinki", "Hong Kong", "Honiara", "Islamabad", "Jakarta", "Jamestown", "Jerusalem", "Juba", "Kabul", "Kampala", "Kathmandu", "Khartoum", "Kiev", "Kigali", "King Edward Point", "Kingston", "Kingstown", "Kinshasa", "Kuala Lumpur", "Kutaisi","Kuwait City", "La Paz", "Libreville", "Lilongwe", "Lima", "Lisbon", "Ljubljana", "Lome", "London", "Luanda", "Lusaka", "Luxembourg", "Madrid", "Majuro", "Malabo", "Malé", "Mamoudzou", "Managua", "Manama", "Manila", "Maputo", "Marigot", "Maseru", "Mata Utu", "Mbabane", "Mexico City", "Minsk", "Mogadishu", "Monaco", "Monrovia", "Montevideo", "Moroni", "Moscow", "Muscat", "Nairobi", "Nassau", "Naypyidaw", "Ndjamena", "New Delhi", "Ngerulmud", "Niamey", "Nicosia", "Nouakchott", "Noumea", "Nukualofa", "Nuuk", "Oranjestad", "Oslo", "Ottawa", "Ouagadougou", "Pago Pago", "Palikir", "Panama City", "Papeete", "Paramaribo", "Paris", "Philipsburg", "Phnom Penh", "Plymouth", "Podgorica", "Port Louis", "Port Moresby", "Port Vila", "Port au Prince", "Port of Spain", "Porto Novo", "Prague", "Praia", "Pretoria", "Pristina", "Putrajaya", "Pyongyang", "Quito", "Rabat", "Reykjavik", "Riga", "Riyadh", "Road Town", "Rome", "Roseau", "Saint Denis", "Saipan", "San Jose", "San Juan", "San Marino", "San Salvador", "Sanaa", "Santiago", "Sao Tome", "Sarajevo", "Seoul", "Singapore", "Skopje", "Sofia", "Sri Jayawardenepura Kotte", "Saint Georges", "Saint Helier", "Saint Johns", "Saint Peter Port", "Saint Pierre", "Stanley", "Stockholm", "Sucre", "Sukhumi", "Suva", "Taipei", "Tallinn", "Tarawa Atoll", "Tashkent", "Tbilisi", "Tegucigalpa", "Tehran", "Thimphu", "Tirana", "Tiraspol", "Tokyo", "Torshavn", "Tripoli", "Tskhinvali", "Tunis", "Ulaanbaatar", "Vaduz", "Valletta", "The Valley", "Vatican City", "Victoria", "Vienna", "Vientiane", "Vilnius", "Warsaw", "Washington D.C.", "Wellington", "West Island", "Willemstad", "Windhoek", "Yamoussoukro", "Yaounde", "Yaren", "Yerevan", "Zagreb"];
   
window.currencies = [
    "Argentine Peso", 
    "Arubian Guilder", 
    "Australian Dollar", 
    "Armenian Dram", 
    "Azerbaijan Manat", 
    "Bahamian Dollar", 
    "Bahraini Dinar", 
    "Bangladeshi Taka", 
    "Barbadian Dollar", 
    "Barbadian Dollar", 
    "Belizean Dollar", 
    "Bermudian Dollar", 
    "Bhutanese Ngultrum", 
    "Bolivian Boliviano", 
    "Botswana  Pula", 
    "Brazilian Real", 
    "Bruneian Dollar", 
    "Bulgarian Lev", 
    "Burmese Kyat", 
    "Cape Verde Escudo", 
    "Cambodian  Riel", 
    "Canadian Dollar", 
    "Chilean Peso", 
    "Chinese Yuan", 
    "Chinese Renminbi", 
    "Costa Rican Colon", 
    "Croatian Kuna", 
    "Czech Koruna", 
    "Cuban Peso", 
    "Danish Krone", 
    "Djiboutian Franc", 
    "Dominican Peso", 
    "East Caribbean Dollar", 
    "Ethiopian Birr", 
    "Egyptian Pound", 
    "Estonian Kroon", 
    "Euro", 
    "Fijian Dollar", 
    "Gambian Dalasi", 
    "Georgian Lari", 
    "Ghanaian Cedi", 
    "Gibraltar Pound",
    "Great British Pound", 
    "Honduran Lempira", 
    "Hong Kong Dollar", 
    "Hungarian Forint", 
    "Icelandic Krona", 
    "Indian Rupee", 
    "Indonesian Rupiah", 
    "Iranian Rial", 
    "Iraqi Dinar", 
    "Israeli Sheqel", 
    "Jamaican Dollar", 
    "Japanese Yen", 
    "Jordanian Dinar", 
    "Kazakhstani Tenge",
    "Kenyan Shilling", 
    "Kuwaiti Dinar", 
    "Kyrgyzstani Som", 
    "Latvian Lats", 
    "Lebanese Pound", 
    "Lesotho Loti", 
    "Liberian Dollar", 
    "Lithuanian Litas", 
    "Libyan Dollar", 
    "Macanese Pataca", 
    "Macedonian Denar", 
    "Malagasy Franc", 
    "Mauritanian Ouguiya", 
    "Mauritian Rupee", 
    "Malawi Kwacha", 
    "Malaysian Ringgit", 
    "Maldivian  Rufiya", 
    "Maltese Lira",
    "Mexican Peso", 
    "Moldovan Leu", 
    "Mongolian Tugrik", 
    "Moroccan Dirham", 
    "Mozambican  Metical", 
    "Namibian Dollar", 
    "Nepalese Rupee", 
    "New Zealand Dollar", 
    "New Taiwan Dollar", 
    "Nigerian Naira", 
    "Norwegian Krone", 
    "North Korean Won", 
    "Omani Rial", 
    "Pakistani Rupee", 
    "Panamanian Balboa", 
    "Philippine Peso", 
    "Polish Zloty", 
    "Qatari Riyal", 
    "Romanian Leu", 
    "Russian Rouble", 
    "Salvadoran Colón", 
    "Saudi Riyal", 
    "Senegal CFA Franc", 
    "Serbian Dinar", 
    "Seychelles Rupee", 
    "Singapore Dollar", 
    "Slovakian Koruna", 
    "South African Rand", 
    "South Korean Won", 
    "Sri Lankan Rupee", 
    "Sudanese Pound", 
    "Suriname Guilder", 
    "Swaziland Lilangeni", 
    "Swedish Krona", 
    "Swiss Franc", 
    "Syrian Pound", 
    "Tajikistani Somoni", 
    "Tanzanian Shilling", 
    "Thai Baht", 
    "Tanzanian Shilling", 
    "Trinidad and Tobago Dollar", 
    "Tunisian Dinar", 
    "Turkish Lira", 
    "Turkmenistan Manat", 
    "Ukranian Hryvnia", 
    "United Arab Emirates Dirham", 
    "Uruguayian Peso", 
    "US Dollar", 
    "Uzbekistan Sum", 
    "Venezuelan Bolivar", 
    "Vietnamese Dong", 
    "West African CFA Franc", 
    "Yemeni Rial", 
    "Zambian Kwacha", 
    "Zimbabwean Dollar"];